# Generated by Django 6.0.2 on 2026-06-25 19:44
#
# Squash of legacy core migrations 0001–0008. Schema generated by makemigrations
# (indexes carry explicit names); reference-data seeds (RSS sources, additional
# sources, static points, market symbols) are re-attached below as idempotent
# RunPython operations.

import django.db.models.deletion
import django_mongodb_backend.fields
import json
import os
import uuid
from django.db import migrations, models


_FIXTURES_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), '..', '..', 'core', 'fixtures')
)

_INITIAL_SOURCE_CODES = [
    'bbc-world', 'aljazeera-world', 'guardian-world', 'france24-world',
    'dw-world', 'rfi-world', 'npr-world', 'rt-world', 'tass-world',
    'xinhua-world', 'middle-east-eye', 'dawn-pk', 'scmp-world',
    'techcrunch', 'the-verge', 'ars-technica', 'wired', 'mit-tech-review',
    'reuters-business', 'economist-finance', 'guardian-economics',
]

_ADDITIONAL_SOURCE_CODES = [
    'reuters-world', 'ap-top', 'voa-world', 'politico-eu', 'japan-times',
    'africa-news', 'bbc-middle-east', 'straits-times', 'foreign-policy',
    'ft-world', 'bloomberg-markets', 'forbes-business', 'wsj-markets',
    'imf-news', 'world-bank-blog', 'project-syndicate', 'brookings',
    'oecd-news', 'guardian-crime', 'reuters-crime', 'interpol-news',
    'un-crime', 'propublica', 'occrp', 'venturebeat', 'zdnet',
    'ieee-spectrum', 'engadget', 'cnet-tech', 'merco-press', 'elpais-english',
    'allafrica', 'arab-news', 'cna-world', 'daily-sabah', 'kyiv-independent',
    'defense-news', 'who-news',
]

_STATIC_POINT_CODES = [
    'NYSE', 'NASDAQ', 'LSE', 'TSE', 'SSE', 'HKEX', 'XETRA', 'EURONEXT-PAR', 'TSX', 'BSE',
    'SGX', 'KRX', 'SIX', 'MOEX', 'ASX', 'DFM', 'JSE', 'B3', 'TADAWUL', 'BIST',
    'CME', 'NYMEX', 'LME', 'ICE-LON', 'DCE', 'SHFE', 'TOCOM',
    'PORT-ROTTERDAM', 'PORT-SINGAPORE', 'PORT-SHANGHAI', 'PORT-SHENZHEN', 'PORT-HONGKONG',
    'PORT-NINGBO', 'PORT-BUSAN', 'PORT-JEBEL-ALI', 'PORT-LA', 'PORT-HAMBURG',
    'PORT-ANTWERP', 'PORT-NY', 'PORT-GUANGZHOU', 'PORT-KAOHSIUNG', 'PORT-SANTOS',
    'PORT-DURBAN', 'PORT-MUMBAI', 'PORT-FELIXSTOWE', 'PORT-SUEZ', 'PORT-COLOMBO',
    'FED', 'ECB', 'BOE', 'BOJ', 'PBOC', 'RBA', 'SNB', 'BOC', 'RBI', 'CBR', 'BCB',
    'SARB', 'BOK', 'MAS', 'SAMA', 'BANXICO', 'TCMB', 'CBE', 'NORGES', 'RIKSBANK', 'BI',
]

_MARKET_SYMBOLS = [
    # (symbol, name, stream_key, provider, provider_id, group,
    #  is_active, is_forecast, is_popular, rank, display_order)
    ('CL=F',      'Crude Oil',              'commodity', 'yahoo',     '',            'resource',   True, True,  True,  1, 1),
    ('GC=F',      'Gold',                   'commodity', 'yahoo',     '',            'resource',   True, True,  True,  0, 0),
    ('BTC-USD',   'Bitcoin',                'crypto',    'coingecko', 'bitcoin',     'top_crypto', True, True,  True,  0, 0),
    ('SPY',       'S&P 500 ETF',            'stock',     'yahoo',     '',            'top_stock',  True, True,  True,  0, 0),
    ('EURUSD=X',  'EUR/USD',                'forex',     'yahoo',     '',            'forex',      True, True,  True,  0, 0),
    ('NG=F',      'Natural Gas',            'commodity', 'yahoo',     '',            'resource',   True, False, True,  2, 2),
    ('ZW=F',      'Wheat',                  'commodity', 'yahoo',     '',            'resource',   True, False, False, 0, 3),
    ('ZC=F',      'Corn',                   'commodity', 'yahoo',     '',            'resource',   True, False, False, 0, 4),
    ('SI=F',      'Silver',                 'commodity', 'yahoo',     '',            'resource',   True, False, True,  3, 5),
    ('QQQ',       'Nasdaq ETF',             'stock',     'yahoo',     '',            'top_stock',  True, False, True,  1, 1),
    ('^GSPC',     'S&P 500',                'stock',     'yahoo',     '',            'index',      True, False, True,  4, 0),
    ('^FTSE',     'FTSE 100',               'stock',     'yahoo',     '',            'index',      True, False, False, 0, 1),
    ('^GDAXI',    'DAX',                    'stock',     'yahoo',     '',            'index',      True, False, False, 0, 2),
    ('^N225',     'Nikkei 225',             'stock',     'yahoo',     '',            'index',      True, False, False, 0, 3),
    ('000001.SS', 'Shanghai Composite',     'stock',     'yahoo',     '',            'index',      True, False, False, 0, 4),
    ('ETH-USD',   'Ethereum',               'crypto',    'coingecko', 'ethereum',    'top_crypto', True, False, True,  1, 1),
    ('XRP-USD',   'XRP',                    'crypto',    'coingecko', 'ripple',      'top_crypto', True, False, False, 0, 2),
    ('SOL-USD',   'Solana',                 'crypto',    'coingecko', 'solana',      'top_crypto', True, False, True,  5, 3),
    ('BNB-USD',   'BNB',                    'crypto',    'coingecko', 'binancecoin', 'top_crypto', True, False, False, 0, 4),
    ('USD/EUR',   'US Dollar / Euro',       'forex',     'ecb',       '',            'forex',      True, False, False, 0, 1),
    ('JPY/EUR',   'Japanese Yen / Euro',    'forex',     'ecb',       '',            'forex',      True, False, False, 0, 2),
    ('GBP/EUR',   'British Pound / Euro',   'forex',     'ecb',       '',            'forex',      True, False, False, 0, 3),
    ('CNY/EUR',   'Chinese Yuan / Euro',    'forex',     'ecb',       '',            'forex',      True, False, False, 0, 4),
    ('CHF/EUR',   'Swiss Franc / Euro',     'forex',     'ecb',       '',            'forex',      True, False, False, 0, 5),
    ('^TNX',      'US 10Y Treasury',        'bond',      'yahoo',     '',            'bond',       True, False, False, 0, 0),
    ('^TYX',      'US 30Y Treasury',        'bond',      'yahoo',     '',            'bond',       True, False, False, 0, 1),
    ('^VIX',      'Volatility Index',       'index',     'yahoo',     '',            'index',      True, False, False, 0, 5),
    ('DX-Y.NYB',  'US Dollar Index',        'index',     'yahoo',     '',            'index',      True, False, False, 0, 6),
]


# ── Data seed helpers ──────────────────────────────────────────────────────────

def _load_fixture(filename, apps, model_label):
    Model = apps.get_model('core', model_label)
    path = os.path.join(_FIXTURES_DIR, filename)
    with open(path, encoding='utf-8') as f:
        entries = json.load(f)
    existing = set(Model.objects.values_list('code', flat=True))
    # Fixture files evolve with the CURRENT model (e.g. sitemap_url, added in
    # 0006, is present in them for fresh installs), but this historical model
    # only has its 0001-era fields — drop anything newer here and let the
    # later data migrations (0007, ...) backfill those columns once they exist.
    allowed = {f.name for f in Model._meta.concrete_fields}
    created = 0
    for entry in entries:
        fields = {k: v for k, v in entry['fields'].items() if k in allowed}
        if fields['code'] not in existing:
            Model.objects.create(**fields)
            created += 1
    print(f'\n[migration] {model_label}: created {created}, skipped {len(entries) - created} existing.')


def load_rss_sources(apps, schema_editor):
    _load_fixture('initial_rss_sources.json', apps, 'Source')


def unload_rss_sources(apps, schema_editor):
    apps.get_model('core', 'Source').objects.filter(code__in=_INITIAL_SOURCE_CODES).delete()


def load_additional_sources(apps, schema_editor):
    _load_fixture('additional_sources.json', apps, 'Source')


def unload_additional_sources(apps, schema_editor):
    apps.get_model('core', 'Source').objects.filter(code__in=_ADDITIONAL_SOURCE_CODES).delete()


def load_static_points(apps, schema_editor):
    StaticPoint = apps.get_model('core', 'StaticPoint')
    path = os.path.join(_FIXTURES_DIR, 'static_points.json')
    with open(path, encoding='utf-8') as f:
        entries = json.load(f)
    existing = set(StaticPoint.objects.values_list('code', flat=True))
    created = 0
    for entry in entries:
        fields = entry['fields']
        if fields['code'] not in existing:
            StaticPoint.objects.create(**fields)
            created += 1
    print(f'\n[migration] StaticPoint: created {created}, skipped {len(entries) - created} existing.')


def unload_static_points(apps, schema_editor):
    apps.get_model('core', 'StaticPoint').objects.filter(code__in=_STATIC_POINT_CODES).delete()


def seed_market_symbols(apps, schema_editor):
    MarketSymbol = apps.get_model('core', 'MarketSymbol')
    created = 0
    for (symbol, name, stream_key, provider, provider_id, group,
         is_active, is_forecast, is_popular, rank, display_order) in _MARKET_SYMBOLS:
        _, was_created = MarketSymbol.objects.update_or_create(
            symbol=symbol,
            defaults=dict(
                name=name, stream_key=stream_key, provider=provider,
                provider_id=provider_id, group=group, is_active=is_active,
                is_forecast=is_forecast, is_popular=is_popular, rank=rank,
                display_order=display_order,
            ),
        )
        created += int(was_created)
    print(f'\n[migration] MarketSymbol: seeded {created}, updated {len(_MARKET_SYMBOLS) - created} existing.')


def unseed_market_symbols(apps, schema_editor):
    syms = [row[0] for row in _MARKET_SYMBOLS]
    apps.get_model('core', 'MarketSymbol').objects.filter(symbol__in=syms).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usgs_id', models.CharField(max_length=32, unique=True)),
                ('magnitude', models.FloatField()),
                ('magnitude_type', models.CharField(blank=True, max_length=8)),
                ('depth_km', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('occurred_at', models.DateTimeField()),
                ('tsunami_alert', models.BooleanField(default=False)),
                ('alert_level', models.CharField(blank=True, max_length=16)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['occurred_at'], name='core_earthq_occurre_0b8b8c_idx'), models.Index(fields=['magnitude'], name='core_earthq_magnitu_41d2bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('conflict', 'Conflict'), ('disaster', 'Disaster'), ('economic', 'Economic'), ('political', 'Political'), ('health', 'Health'), ('general', 'General'), ('protest', 'Protest'), ('crime', 'Crime')], default='general', max_length=64)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(help_text='Timestamp of the earliest article')),
                ('latest_article_at', models.DateTimeField(blank=True, null=True)),
                ('article_count', models.IntegerField(default=1)),
                ('avg_sentiment', models.FloatField(blank=True, null=True)),
                ('avg_finbert_sentiment', models.FloatField(blank=True, null=True)),
                ('avg_intensity', models.FloatField(blank=True, null=True)),
                ('affected_indicators', models.JSONField(blank=True, default=list)),
                ('router_source', models.CharField(blank=True, default='rules', max_length=8)),
                ('article_ids', models.JSONField(default=list)),
                ('source_codes', models.JSONField(default=list)),
                ('sub_categories', models.JSONField(blank=True, default=list)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('topics', models.JSONField(blank=True, default=dict)),
                ('topic_slugs', models.JSONField(blank=True, default=list)),
                ('topics_source', models.CharField(blank=True, default='', max_length=8)),
                ('stage_status', models.JSONField(blank=True, default=dict)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['started_at'], name='core_event_started_9ab2e7_idx'), models.Index(fields=['latest_article_at'], name='core_event_latest__idx'), models.Index(fields=['category'], name='core_event_categor_0ee9fa_idx'), models.Index(fields=['location_name'], name='core_event_locatio_09eaed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('stream_key', models.CharField(blank=True, max_length=32)),
                ('generated_at', models.DateTimeField()),
                ('as_of_date', models.DateTimeField()),
                ('horizon_days', models.IntegerField(default=1)),
                ('direction', models.CharField(default='neutral', max_length=8)),
                ('proba_up', models.FloatField(default=0.5)),
                ('predicted_change_pct', models.FloatField(default=0.0)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('band_low', models.FloatField(blank=True, null=True)),
                ('band_high', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('router_source', models.CharField(default='rules', max_length=8)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('realized_direction', models.CharField(blank=True, max_length=8, null=True)),
                ('realized_change_pct', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['symbol', 'horizon_days', 'generated_at'], name='core_foreca_symbol_e70804_idx'), models.Index(fields=['as_of_date'], name='core_foreca_as_of_d_8596f3_idx'), models.Index(fields=['generated_at'], name='core_foreca_generat_1afbef_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketSymbol',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('stream_key', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('commodity', 'Commodity'), ('forex', 'Forex'), ('bond', 'Bond'), ('index', 'Index')], default='stock', max_length=16)),
                ('provider', models.CharField(choices=[('yahoo', 'Yahoo Finance'), ('coingecko', 'CoinGecko'), ('ecb', 'ECB (forex)')], default='yahoo', max_length=16)),
                ('provider_id', models.CharField(blank=True, max_length=64)),
                ('group', models.CharField(choices=[('top_stock', 'Top Stock'), ('top_crypto', 'Top Crypto'), ('resource', 'Resource / Commodity'), ('forex', 'Forex'), ('bond', 'Bond'), ('index', 'Index'), ('other', 'Other')], default='other', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_forecast', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('rank', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'display_order', 'symbol'],
                'indexes': [models.Index(fields=['stream_key', 'is_active'], name='core_market_stream__588ccd_idx'), models.Index(fields=['is_forecast'], name='core_market_is_fore_074aaf_idx'), models.Index(fields=['group'], name='core_market_group_93c77a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotamRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notam_id', models.CharField(max_length=128, unique=True)),
                ('source_region', models.CharField(max_length=32)),
                ('notam_type', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('geometry', models.JSONField(default=dict)),
                ('altitude_min_ft', models.IntegerField(blank=True, null=True)),
                ('altitude_max_ft', models.IntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('raw_text', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['effective_from', 'effective_to'], name='core_notamr_effecti_9c37ae_idx'), models.Index(fields=['status'], name='core_notamr_status_2456bd_idx'), models.Index(fields=['country_code'], name='core_notamr_country_e7fe20_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotamZone',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notam_id', models.CharField(max_length=128, unique=True)),
                ('notam_type', models.CharField(max_length=32)),
                ('geometry', models.JSONField(default=dict)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=4)),
                ('altitude_min_ft', models.IntegerField(blank=True, null=True)),
                ('altitude_max_ft', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['is_active'], name='core_notamz_is_acti_b7fb52_idx'), models.Index(fields=['effective_to'], name='core_notamz_effecti_b8d28e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceBar',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('stream_key', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=64)),
                ('interval', models.CharField(default='1d', max_length=8)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField()),
                ('volume', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'date'], name='core_priceb_symbol_50224d_idx'), models.Index(fields=['date'], name='core_priceb_date_e212e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32)),
                ('stream_key', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('change_pct', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['symbol', 'occurred_at'], name='core_pricet_symbol_983d49_idx'), models.Index(fields=['stream_key'], name='core_pricet_stream__2bdb1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier for the source', max_length=64, unique=True)),
                ('type', models.CharField(choices=[('website', 'Website'), ('api', 'Api'), ('rss', 'Rss'), ('social', 'Social'), ('email', 'Email'), ('newsletter', 'Newsletter'), ('database', 'Database')], max_length=64)),
                ('name', models.CharField(help_text='Display name of the source', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, default='', help_text='URL of the source, used in website and RSS feeds', max_length=255)),
                ('author_slug', models.CharField(blank=True, default='', help_text='Author/slug of the source', max_length=255)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True, help_text='Uncheck to disable fetching from this source')),
                ('weight', models.FloatField(default=1.0, help_text='Importance score multiplier (0.1–2.0)')),
                ('weight_locked', models.BooleanField(default=False, help_text='Prevent auto-weight adjustment')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['created_on'], name='core_source_created_26fa74_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaticPoint',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('point_type', models.CharField(choices=[('exchange', 'Stock Exchange'), ('commodity_exchange', 'Commodity Exchange'), ('port', 'Major Port'), ('central_bank', 'Central Bank')], max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=64)),
                ('country_code', models.CharField(max_length=4)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['point_type', 'name'],
                'indexes': [models.Index(fields=['point_type'], name='core_static_point_t_bb5f0e_idx'), models.Index(fields=['country_code'], name='core_static_country_5c3f60_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128)),
                ('queue', models.CharField(default='default', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('items', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('job_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['task_name', 'started_at'], name='core_taskru_task_na_1a1736_idx'), models.Index(fields=['status'], name='core_taskru_status_267cbb_idx'), models.Index(fields=['started_at'], name='core_taskru_started_64bfc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('conflict', 'Conflict'), ('disaster', 'Disaster'), ('economic', 'Economic'), ('political', 'Political'), ('health', 'Health'), ('general', 'General'), ('protest', 'Protest'), ('crime', 'Crime')], max_length=64)),
                ('source_url', models.URLField(blank=True, max_length=512)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('is_current', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When this topic first appeared in the news', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When this topic resolved or faded. Null means still ongoing.', null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('parent_slug', models.CharField(blank=True, max_length=128, null=True)),
                ('historical_month', models.IntegerField(blank=True, null=True)),
                ('historical_day', models.IntegerField(blank=True, null=True)),
                ('historical_year', models.IntegerField(blank=True, null=True)),
                ('event_count', models.IntegerField(default=0)),
                ('topic_score', models.FloatField(default=0.0, help_text='Composite ranking score, updated by tag_topics_task.')),
                ('is_pinned', models.BooleanField(default=False, help_text='Admin override: always shown in header, never auto-demoted.')),
                ('is_top_level', models.BooleanField(default=False, help_text='Auto-set: shown in UI header when score passes threshold.')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_current'], name='core_topic_is_curr_ff956c_idx'), models.Index(fields=['is_active'], name='core_topic_is_acti_37701b_idx'), models.Index(fields=['is_top_level'], name='core_topic_is_top__f4d612_idx'), models.Index(fields=['category'], name='core_topic_categor_6a12b8_idx'), models.Index(fields=['started_at'], name='core_topic_started_1764c0_idx'), models.Index(fields=['ended_at'], name='core_topic_ended_a_d6c923_idx'), models.Index(fields=['parent_slug'], name='core_topic_parent__0f1fb8_idx'), models.Index(fields=['historical_month', 'historical_day'], name='core_topic_histori_bcdeea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_code', models.CharField(max_length=64)),
                ('source_type', models.CharField(choices=[('website', 'Website'), ('api', 'Api'), ('rss', 'Rss'), ('social', 'Social'), ('email', 'Email'), ('newsletter', 'Newsletter'), ('database', 'Database')], max_length=64)),
                ('source_url', models.URLField(max_length=512)),
                ('author', models.CharField(max_length=100)),
                ('author_slug', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_on', models.DateTimeField()),
                ('entities', models.JSONField(blank=True, default=list)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('finbert_sentiment', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('event_intensity', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('conflict', 'Conflict'), ('disaster', 'Disaster'), ('economic', 'Economic'), ('political', 'Political'), ('health', 'Health'), ('general', 'General'), ('protest', 'Protest'), ('crime', 'Crime')], help_text='Rule-based event category', max_length=64, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=64, null=True)),
                ('processed_on', models.DateTimeField(blank=True, null=True)),
                ('importance_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('importance_source', models.CharField(blank=True, max_length=16, null=True)),
                ('stage_status', models.JSONField(blank=True, default=dict)),
                ('banner_image_url', models.URLField(blank=True, max_length=512, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.article')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['created_on'], name='core_articl_created_7c1afd_idx'), models.Index(fields=['source_code'], name='core_articl_source__16229e_idx'), models.Index(fields=['author_slug'], name='core_articl_author__a84eca_idx'), models.Index(fields=['category'], name='core_articl_categor_1aa045_idx'), models.Index(fields=['processed_on'], name='core_articl_process_0f6d5b_idx'), models.Index(fields=['location'], name='core_articl_locatio_205cda_idx')],
            },
        ),

        # ── Reference-data seeds (idempotent) ─────────────────────────────────
        migrations.RunPython(load_rss_sources,        reverse_code=unload_rss_sources),
        migrations.RunPython(load_additional_sources, reverse_code=unload_additional_sources),
        migrations.RunPython(load_static_points,      reverse_code=unload_static_points),
        migrations.RunPython(seed_market_symbols,     reverse_code=unseed_market_symbols),
    ]
