# Generated by Django 6.0.6 on 2026-07-21 20:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_article_refined_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_on']},
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='core_event_is_rout_674eca_idx',
            old_name='core_event_is_routed_idx',
        ),
        migrations.RenameIndex(
            model_name='forecast',
            new_name='core_foreca_realize_3e6469_idx',
            old_name='core_foreca_realize_idx',
        ),
        # State-only: register is_deleted with Django WITHOUT the collection-wide
        # update_many({}, {$set: {is_deleted: False}}) that a plain AddField runs
        # on this backend (django_mongodb_backend/schema.py add_field) — that
        # rewrites every article and makes deploy take ages on the 100k+ corpus.
        # Mongo is schemaless, so no write is needed: the field materializes
        # lazily as (deferred) annotate marks junk, and AliveMongoManager's
        # exclude(is_deleted=True) treats absent-or-false as not-deleted.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='article',
                    name='is_deleted',
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[],
        ),
    ]
